### ISSUE TITLE
Displaying error when type is not defined

### ISSUE THREAD

**Issue by LarryBarker** [inetis-ch/october-schemas#1]
Great extension here! Am noticing one minor annoyance when fields don't have a type explicitly defined, the field is displaying an error:
 
![image](https://user-images.githubusercontent.com/28734844/78927813-1e7cc380-7a65-11ea-8cde-64d69195fdf3.png)

By default, the form controller will render fields without `type` specified as a text field. Should we make this display as a warning or hint and let the user know if no type is provided it will render as a text input?

**Comment by ChVuagniaux** [comment]
Thanks for the feedback, I made this field optional according to the documentation
